import Link from 'next/link'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { ChevronLeft, Shield, AlertTriangle } from 'lucide-react'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-slate-100">
      {/* Header */}
      <header className="bg-white border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
              <span className="font-bold text-white">€</span>
            </div>
            <span className="font-bold text-xl text-slate-900">NebenkostenAI</span>
          </Link>
        </div>
      </header>

      <main className="py-12 px-4">
        <div className="max-w-3xl mx-auto">
          <Link href="/" className="inline-flex items-center text-sm text-slate-600 hover:text-slate-900 mb-6">
            <ChevronLeft className="w-4 h-4 mr-1" />
            Back to Home
          </Link>

          <Card>
            <CardHeader>
              <CardTitle className="text-2xl">Terms of Service</CardTitle>
              <CardDescription>
                Last updated: February 18, 2025
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-8">
              {/* Disclaimer Banner */}
              <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 flex gap-3">
                <AlertTriangle className="w-6 h-6 text-amber-600 flex-shrink-0" />
                <div>
                  <h3 className="font-semibold text-amber-900">Important Legal Disclaimer</h3>
                  <p className="text-sm text-amber-800 mt-1">
                    NebenkostenAI is a statistical calculation tool and does not provide legal advice. 
                    All reports, analyses, and generated documents are for informational purposes only.
                  </p>
                </div>
              </div>

              <section>
                <h2 className="text-lg font-semibold mb-3">1. Nature of Service</h2>
                <p className="text-slate-600 text-sm leading-relaxed">
                  NebenkostenAI is an automated analysis tool that uses statistical benchmarks and 
                  keyword detection to identify potential errors in German utility bills 
                  (Betriebskostenabrechnung). Our service does not constitute:
                </p>
                <ul className="mt-2 space-y-1 text-sm text-slate-600 list-disc list-inside">
                  <li>Legal advice or legal representation</li>
                  <li>Professional accounting or tax advice</li>
                  <li>A guarantee of any specific outcome or refund</li>
                  <li>A substitute for consultation with qualified legal professionals</li>
                </ul>
              </section>

              <section>
                <h2 className="text-lg font-semibold mb-3">2. No Attorney-Client Relationship</h2>
                <p className="text-slate-600 text-sm leading-relaxed">
                  Use of NebenkostenAI does not create an attorney-client relationship. 
                  The objection letters (Widerspruch) generated by our service are templates 
                  based on user-provided data and statistical analysis. They are provided "as is" 
                  without any warranty of correctness, completeness, or legal validity.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold mb-3">3. User Responsibility</h2>
                <p className="text-slate-600 text-sm leading-relaxed">
                  You are solely responsible for:
                </p>
                <ul className="mt-2 space-y-1 text-sm text-slate-600 list-disc list-inside">
                  <li>Verifying the accuracy of all information entered into our system</li>
                  <li>Reviewing and customizing any generated documents before use</li>
                  <li>Ensuring compliance with applicable laws and regulations</li>
                  <li>Seeking professional legal advice for your specific situation</li>
                </ul>
              </section>

              <section>
                <h2 className="text-lg font-semibold mb-3">4. Limitation of Liability</h2>
                <p className="text-slate-600 text-sm leading-relaxed">
                  To the maximum extent permitted by law, NebenkostenAI and its operators shall not be 
                  liable for any direct, indirect, incidental, special, consequential, or punitive 
                  damages arising from your use of our service, including but not limited to:
                </p>
                <ul className="mt-2 space-y-1 text-sm text-slate-600 list-disc list-inside">
                  <li>Disputes with landlords or property managers</li>
                  <li>Failed or rejected objections</li>
                  <li>Incorrect analysis results or missed errors</li>
                  <li>Costs incurred from using generated documents</li>
                </ul>
              </section>

              <section>
                <h2 className="text-lg font-semibold mb-3">5. Refund Policy</h2>
                <p className="text-slate-600 text-sm leading-relaxed">
                  Due to the digital nature of our reports and immediate delivery upon payment, 
                  all sales are final. However, if you experience technical issues that prevent 
                  you from accessing your report, please contact us within 14 days for assistance.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold mb-3">6. Data Processing</h2>
                <p className="text-slate-600 text-sm leading-relaxed">
                  We process your uploaded documents solely for the purpose of providing our analysis 
                  service. Files are stored securely and are not shared with third parties except 
                  as necessary to perform the service (e.g., OpenAI for OCR processing). 
                  You retain all rights to your documents.
                </p>
              </section>

              <section>
                <h2 className="text-lg font-semibold mb-3">7. Governing Law</h2>
                <p className="text-slate-600 text-sm leading-relaxed">
                  These terms are governed by the laws of the Federal Republic of Germany. 
                  Any disputes shall be resolved in the courts of Berlin, Germany.
                </p>
              </section>

              <div className="bg-slate-50 rounded-lg p-4 text-center">
                <p className="text-sm text-slate-600">
                  By using NebenkostenAI, you acknowledge that you have read, understood, 
                  and agree to these terms of service.
                </p>
              </div>

              <div className="flex justify-center">
                <Link href="/">
                  <Button variant="outline">
                    <ChevronLeft className="w-4 h-4 mr-2" />
                    Return to Home
                  </Button>
                </Link>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}
