'use client'

import { Document, Page, Text, View, StyleSheet, PDFDownloadLink } from '@react-pdf/renderer'
import { Button } from '@/components/ui/button'
import { FileDown } from 'lucide-react'

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: 'Helvetica',
    fontSize: 12
  },
  header: {
    fontSize: 24,
    marginBottom: 20,
    color: '#1e293b',
    fontWeight: 'bold'
  },
  subheader: {
    fontSize: 16,
    marginBottom: 10,
    color: '#334155',
    fontWeight: 'bold',
    marginTop: 15
  },
  text: {
    fontSize: 12,
    marginBottom: 8,
    color: '#475569'
  },
  summary: {
    backgroundColor: '#f8fafc',
    padding: 15,
    marginBottom: 20,
    borderRadius: 8
  },
  errorItem: {
    marginBottom: 12,
    padding: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#ef4444',
    backgroundColor: '#fef2f2'
  },
  warningItem: {
    marginBottom: 12,
    padding: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#f59e0b',
    backgroundColor: '#fffbeb'
  },
  goodItem: {
    marginBottom: 12,
    padding: 10,
    borderLeftWidth: 4,
    borderLeftColor: '#10b981',
    backgroundColor: '#f0fdf4'
  },
  footer: {
    marginTop: 30,
    fontSize: 10,
    color: '#94a3b8',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingTop: 15
  }
})

interface PDFReportProps {
  billData: {
    file_name: string
    billing_period?: string
    total_square_meters?: number
    total_cost?: number
    verified_data?: any
  }
  analysisResult: {
    lineItems: any[]
    totalErrors: number
    formalErrors: number
    outliers: number
    estimatedRefund: number
  }
}

const PDFReport = ({ billData, analysisResult }: PDFReportProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>NebenkostenAI Analysis Report</Text>
      
      <View style={styles.summary}>
        <Text style={styles.subheader}>Bill Summary</Text>
        <Text style={styles.text}>File: {billData.file_name}</Text>
        {billData.billing_period && (
          <Text style={styles.text}>Period: {billData.billing_period}</Text>
        )}
        {billData.total_square_meters && (
          <Text style={styles.text}>Apartment Size: {billData.total_square_meters} sqm</Text>
        )}
        {billData.total_cost && (
          <Text style={styles.text}>Total Cost: €{billData.total_cost.toFixed(2)}</Text>
        )}
      </View>

      <View style={styles.summary}>
        <Text style={styles.subheader}>Analysis Summary</Text>
        <Text style={styles.text}>Total Errors Found: {analysisResult.totalErrors}</Text>
        <Text style={styles.text}>Formal Errors (Illegal Charges): {analysisResult.formalErrors}</Text>
        <Text style={styles.text}>Statistical Outliers: {analysisResult.outliers}</Text>
        <Text style={styles.text}>Estimated Potential Refund: €{analysisResult.estimatedRefund.toFixed(2)}</Text>
      </View>

      <Text style={styles.subheader}>Detailed Analysis</Text>
      
      {analysisResult.lineItems.map((item, index) => (
        <View 
          key={index} 
          style={
            item.score === 'red' ? styles.errorItem : 
            item.score === 'yellow' ? styles.warningItem : 
            styles.goodItem
          }
        >
          <Text style={{ fontWeight: 'bold', marginBottom: 4 }}>
            {item.name} - €{item.total_cost?.toFixed(2)}
          </Text>
          {item.error_details && (
            <Text style={{ color: item.score === 'red' ? '#dc2626' : '#d97706' }}>
              {item.error_details}
            </Text>
          )}
          {!item.error_details && (
            <Text style={{ color: '#059669' }}>No issues detected</Text>
          )}
        </View>
      ))}

      <View style={styles.footer}>
        <Text>This report was generated by NebenkostenAI and is for informational purposes only.</Text>
        <Text>It does not constitute legal advice. Please consult a legal professional for formal action.</Text>
        <Text>Generated on: {new Date().toLocaleDateString('de-DE')}</Text>
      </View>
    </Page>
  </Document>
)

export function PDFDownloadButton({ billData, analysisResult }: PDFReportProps) {
  return (
    <PDFDownloadLink
      document={<PDFReport billData={billData} analysisResult={analysisResult} />}
      fileName={`nebenkosten-analysis-${billData.file_name}.pdf`}
    >
      {({ loading }) => (
        <Button disabled={loading} variant="outline">
          <FileDown className="w-4 h-4 mr-2" />
          {loading ? 'Generating PDF...' : 'Download PDF Report'}
        </Button>
      )}
    </PDFDownloadLink>
  )
}

export default PDFReport
